
### 3. What is the problem with below program? Recommend a solution.

```java
import java.io.FileNotFoundException;
import java.io.IOException;

public class TestException {
    public static void main(String[] args) {
        try {
            testExceptions();
        } catch (FileNotFoundException | IOException e) {
            e.printStackTrace();
        }
    }

    public static void testExceptions() throws IOException, FileNotFoundException{

    }
}
```
Solution
> IOException which extends Exception class signals that an I/O exception of some sort has occured.
> This class is the general class of exceptions produced by failed or interrupted I/O operations.
> 
> FileNotFoundException which extends IOException class signals that an attempt to open the file 
> denoted by a specified pathname has failed. This excpetion will be thrown by FileInputStream,
> FileOutputStream and RandomAccessFile constructors when a file specified with pathname does not
> exist. This exception will also be thrown when the file is inaccessible, example: when attempting to
> open a read-only file for writing.
> 
> IOException is a more generalised exception of FileNotFoundException. When multicatching exception 
> using pipe syntax, the exceptions caught should be disjoint. So either more specific FileNotFoundException
> or more generalised IOException can be used with pipe syntax but not both together. The solution would be to catch 
> FileNotFoundException in the first catch block and then catch the generic IOException in the second catch block.
> This way, the specific FileNotFoundException exception will be caught first, if it occurs and if any other specific
> IOException occurs, it will be caught by the second block. 

### 4.  What is the problem with below program? Recommend a solution.

```java
public class ExceptionHandling
{
    public static void main(String[] args)
    {
        try
        {
            int i = Integer.parseInt("abc");
        }
        catch(Exception ex)
        {
            System.out.println("This block handles all exception types");
        }
        catch(NumberFormatException ex)
        {
        }
    }
}
```
Solution:
> When organising catch blocks, more specific exceptions should come at the top followed by the generalised 
> ones. Here in the above code, NumberFormatException is a more specific exception. NumberFormatException extends
> Exception class which is a more generalised exception. So in this case, the code should have be as below:

```java
public class ExceptionHandling
{
    public static void main(String[] args)
    {
        try
        {
            int i = Integer.parseInt("abc");
        }
        catch(NumberFormatException ex)
        {
        }
        catch(Exception ex)
        {
            System.out.println("This block handles all exception types");
        }
    }
}
```

### 5. How would you differentiate between throw, throws and throwable in Java?

Answer:
> Throw - keyword is used to throw exception from within a method or from a block of code. Throw can be used 
> with either checked or unchecked exception.
```java
class TestThrowException
{
    public static void main(String[] args)
    {
        try
        {
            throw new NumberFormatException("Number format exception thrown from main().");
        }
        catch(NumberFormatException numberFormatException)
        {
            System.out.println(numberFormatException.getMessage());
            System.out.println("Number format exception caught in catch block");
        }
    }
}
```
> Throws - keyword is used in the method signature to indicate that the method might throw the listed exceptions.
> The caller method is supposed to handle the exception either with the try-catch block or can rethrow the exception
> caught.

```java
class ThrowsDemo{
    public static void main(String[] args) {
        try {
            testThrows();
        }
        catch (IndexOutOfBoundsException indexOutOfBoundsException){
            System.out.println(indexOutOfBoundsException.getMessage()); 
        }
    }
    
    public static void testThrows() throws IndexOutOfBoundsException{
        throw new IndexOutOfBoundsException("Throw IndexOutOfBoundException");
    }
}
```

> Throwable - Throwable class is the parent of all the exception classes. Major methods that this class implements are getMessage(),
> getLocalizedMessage(), getCause() and printStackTrace().

